
server:
  port: 8080

spring:
  cache:
    type: hazelcast
  jpa:
    show-sql: true
    properties:
      hibernate:
        cache:
          use_query_cache: true
          use_second_level_cache: true
          hazelcast:
            use_native_client: true
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory

